export const jobs = [
  {
    id: 1,
    title: "Angular developer",
    description:
      "We are looking for a Front End (Angular) Engineer to join our engineering team at our new office in Warsaw. You will work closely with our development team to improve the quality of our results. Extensive knowledge of Javascript/Typescript  Extensive knowledge of RxJS  Extensive knowledge of design patterns  Commercial experience with Angular 5+ Responsibilities Developing SPA complex applications, internal projects  Would be a plus English Intermediate Work conditions Remote 21 working days of paid vacation English courses  Paid sick leaves Medical insurance About Palavero Inc.Palavero is a Global IT Recruitment Agency dedicated to finding the best match for businesses. We believe that the best people make the best companies, and our goal is to help build a strong and successful teams.Palavero is a unique recruitment agency that offers lower prices, comprehensive recruiting services, expertise in blockchain technology, HR consulting, executive search, headhunting, and potential partnerships and investments for startups. Our services include recruiting training, transparency, big candidate database, multilingual support, technical interview assistance, business development advice, free replacement guarantee and additional services for IT companies.",
    recruiterName: "Natallia Tikhonova",
    companyName: "Palavero Inc",
    companyaddress: {
      country: "Russia",
      city: "Moscow ",
      street: "Maklaya",
      website: "http://www.palavero.com",
    },
    experience: 3,
    skills: [
      "Javascript",
      "Typescript",
      "knowledge of RxJS",
      "knowledge of design patterns",
    ],
    salary: 900,
    englishLevel: "Upper-Intermediate ",
    workConditions: "remote",
    views: 23,
    applicants: 2,
    datePosted: "Today",
  },
  {
    id: 2,
    title: "Angular developer",
    description:
      "We are looking for a Front End (Angular) Engineer to join our engineering team at our new office in Warsaw. You will work closely with our development team to improve the quality of our results. Extensive knowledge of Javascript/Typescript  Extensive knowledge of RxJS  Extensive knowledge of design patterns  Commercial experience with Angular 5+ Responsibilities Developing SPA complex applications, internal projects  Would be a plus English Intermediate Work conditions Remote 21 working days of paid vacation English courses  Paid sick leaves Medical insurance About Palavero Inc.Palavero is a Global IT Recruitment Agency dedicated to finding the best match for businesses. We believe that the best people make the best companies, and our goal is to help build a strong and successful teams.Palavero is a unique recruitment agency that offers lower prices, comprehensive recruiting services, expertise in blockchain technology, HR consulting, executive search, headhunting, and potential partnerships and investments for startups. Our services include recruiting training, transparency, big candidate database, multilingual support, technical interview assistance, business development advice, free replacement guarantee and additional services for IT companies.",
    recruiterName: "Natallia Tikhonova",
    companyName: "Palavero Inc",
    companyaddress: {
      country: "Russia",
      city: "Moscow ",
      street: "Maklaya",
      website: "http://www.palavero.com",
    },
    experience: 3,
    skills: [
      "Javascript",
      "Typescript",
      "knowledge of RxJS",
      "knowledge of design patterns",
    ],
    salary: 900,
    englishLevel: "Upper-Intermediate ",
    workConditions: "remote",
    views: 23,
    applicants: 2,
    datePosted: "Today",
  },
  {
    id: 3,
    title: "Angular developer",
    description:
      "We are looking for a Front End (Angular) Engineer to join our engineering team at our new office in Warsaw. You will work closely with our development team to improve the quality of our results. Extensive knowledge of Javascript/Typescript  Extensive knowledge of RxJS  Extensive knowledge of design patterns  Commercial experience with Angular 5+ Responsibilities Developing SPA complex applications, internal projects  Would be a plus English Intermediate Work conditions Remote 21 working days of paid vacation English courses  Paid sick leaves Medical insurance About Palavero Inc.Palavero is a Global IT Recruitment Agency dedicated to finding the best match for businesses. We believe that the best people make the best companies, and our goal is to help build a strong and successful teams.Palavero is a unique recruitment agency that offers lower prices, comprehensive recruiting services, expertise in blockchain technology, HR consulting, executive search, headhunting, and potential partnerships and investments for startups. Our services include recruiting training, transparency, big candidate database, multilingual support, technical interview assistance, business development advice, free replacement guarantee and additional services for IT companies.",
    recruiterName: "Natallia Tikhonova",
    companyName: "Palavero Inc",
    companyaddress: {
      country: "Russia",
      city: "Moscow ",
      street: "Maklaya",
      website: "http://www.palavero.com",
    },
    experience: 3,
    skills: [
      "Javascript",
      "Typescript",
      "knowledge of RxJS",
      "knowledge of design patterns",
    ],
    salary: 900,
    englishLevel: "Upper-Intermediate ",
    workConditions: "remote",
    views: 23,
    applicants: 2,
    datePosted: "Today",
  },
  {
    id: 4,
    title: "Angular developer",
    description:
      "We are looking for a Front End (Angular) Engineer to join our engineering team at our new office in Warsaw. You will work closely with our development team to improve the quality of our results. Extensive knowledge of Javascript/Typescript  Extensive knowledge of RxJS  Extensive knowledge of design patterns  Commercial experience with Angular 5+ Responsibilities Developing SPA complex applications, internal projects  Would be a plus English Intermediate Work conditions Remote 21 working days of paid vacation English courses  Paid sick leaves Medical insurance About Palavero Inc.Palavero is a Global IT Recruitment Agency dedicated to finding the best match for businesses. We believe that the best people make the best companies, and our goal is to help build a strong and successful teams.Palavero is a unique recruitment agency that offers lower prices, comprehensive recruiting services, expertise in blockchain technology, HR consulting, executive search, headhunting, and potential partnerships and investments for startups. Our services include recruiting training, transparency, big candidate database, multilingual support, technical interview assistance, business development advice, free replacement guarantee and additional services for IT companies.",
    recruiterName: "Natallia Tikhonova",
    companyName: "Palavero Inc",
    companyaddress: {
      country: "Russia",
      city: "Moscow ",
      street: "Maklaya",
      website: "http://www.palavero.com",
    },
    experience: 3,
    skills: [
      "Javascript",
      "Typescript",
      "knowledge of RxJS",
      "knowledge of design patterns",
    ],
    salary: 900,
    englishLevel: "Upper-Intermediate ",
    workConditions: "remote",
    views: 23,
    applicants: 2,
    datePosted: "Today",
  },
  {
    id: 5,
    title: "Angular developer",
    description:
      "We are looking for a Front End (Angular) Engineer to join our engineering team at our new office in Warsaw. You will work closely with our development team to improve the quality of our results. Extensive knowledge of Javascript/Typescript  Extensive knowledge of RxJS  Extensive knowledge of design patterns  Commercial experience with Angular 5+ Responsibilities Developing SPA complex applications, internal projects  Would be a plus English Intermediate Work conditions Remote 21 working days of paid vacation English courses  Paid sick leaves Medical insurance About Palavero Inc.Palavero is a Global IT Recruitment Agency dedicated to finding the best match for businesses. We believe that the best people make the best companies, and our goal is to help build a strong and successful teams.Palavero is a unique recruitment agency that offers lower prices, comprehensive recruiting services, expertise in blockchain technology, HR consulting, executive search, headhunting, and potential partnerships and investments for startups. Our services include recruiting training, transparency, big candidate database, multilingual support, technical interview assistance, business development advice, free replacement guarantee and additional services for IT companies.",
    recruiterName: "Natallia Tikhonova",
    companyName: "Palavero Inc",
    companyaddress: {
      country: "Russia",
      city: "Moscow ",
      street: "Maklaya",
      website: "http://www.palavero.com",
    },
    experience: 3,
    skills: [
      "Javascript",
      "Typescript",
      "knowledge of RxJS",
      "knowledge of design patterns",
    ],
    salary: 900,
    englishLevel: "Upper-Intermediate ",
    workConditions: "remote",
    views: 23,
    applicants: 2,
    datePosted: "Today",
  },
  {
    id: 6,
    title: "Angular developer",
    description:
      "We are looking for a Front End (Angular) Engineer to join our engineering team at our new office in Warsaw. You will work closely with our development team to improve the quality of our results. Extensive knowledge of Javascript/Typescript  Extensive knowledge of RxJS  Extensive knowledge of design patterns  Commercial experience with Angular 5+ Responsibilities Developing SPA complex applications, internal projects  Would be a plus English Intermediate Work conditions Remote 21 working days of paid vacation English courses  Paid sick leaves Medical insurance About Palavero Inc.Palavero is a Global IT Recruitment Agency dedicated to finding the best match for businesses. We believe that the best people make the best companies, and our goal is to help build a strong and successful teams.Palavero is a unique recruitment agency that offers lower prices, comprehensive recruiting services, expertise in blockchain technology, HR consulting, executive search, headhunting, and potential partnerships and investments for startups. Our services include recruiting training, transparency, big candidate database, multilingual support, technical interview assistance, business development advice, free replacement guarantee and additional services for IT companies.",
    recruiterName: "Natallia Tikhonova",
    companyName: "Palavero Inc",
    companyaddress: {
      country: "Russia",
      city: "Moscow ",
      street: "Maklaya",
      website: "http://www.palavero.com",
    },
    experience: 3,
    skills: [
      "Javascript",
      "Typescript",
      "knowledge of RxJS",
      "knowledge of design patterns",
    ],
    salary: 900,
    englishLevel: "Upper-Intermediate ",
    workConditions: "remote",
    views: 23,
    applicants: 2,
    datePosted: "Today",
  },
];
