import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.scss";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.header}>
          <h2>Всё для комфортной работы</h2>
        </div>
        <div className={styles.topDiv}>
          <div className={styles.image}>
            <Image src="/home-images/desk-table.jpg" fill alt="" />
          </div>
          <div className={styles.sqaure}>
            <div className={styles.discount}>- 25%</div>
            <p className={styles.text}>на товары для кабинета</p>
            <p className={styles.choose}>Выбрать</p>
          </div>
        </div>
        <div className={styles.bottomDiv}>
          <div className={styles.image}>
            <Image src="/home-images/images.jpeg" fill alt="" />
          </div>
          <div className={styles.sqaure}>
            <div className={styles.discount}><p>Скидка</p> <div className={styles.span}>10%</div></div>
            <p className={styles.text}>на периферию для компьютера</p>
            <p className={styles.choose}>Выбрать</p>
          </div>
        </div>
      </main>
    </>
  );
}
